Set a pool_recycle value when creating the database connection
We are finding some cases where the connection between the DLRN
instance and the database is lost. This shows up as the following
error message when a package is built:

sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError)
(2013, 'Lost connection to MySQL server during query
([Errno 110] Connection timed out)')

This is usually caused by a server-side socket disconnection, which
can be caused by a MariaDB timeout or other types of network timeout
(for example, firewalls between the client and the server). As a
mitigation measure, we can set a value for pool_recycle when creating
the engine in SQLAlchemy. We are setting a low value (5 mins) to
avoid network issues.

While this creates some overhead for the reconnection, it should not
be a big problem in the current DLRN environment.

Change-Id: I46849a5ccbdbb04948b26779408e51708d1d2912