Require rdopkg >= 0.44.2
rdopkg-0.44.2 includes fix for

    ImportError: No module named rdoinfo

related to `rdopkg info -l LOCALDIR`

Change-Id: I2924d32cd2f4cf6d14f69d56d2883fad2b56bc24