Pin rdopkg<0.47.0 due to backward incompatibility
rdopkg-0.47.0 switched to distroinfo which resulted in backward
incompatible changes that manifests in DLRN as

    AttributeError: 'module' object has no attribute 'RdoinfoRepo'

TODO: This kind of breakage should be detected by rdopkg CI!

rdopkg commits should be gated by DLRN integration tests.

Change-Id: I27c35edf9bc0958c5e104c03dc06e72f936530f2