Pass the $TERM variable to tox
The test "dlrn.tests.test_shell" requires $TERM to be set.
It will otherwise return the error:
error: setupterm: could not find terminal

Change-Id: I860046cc6ff8f2271d46ae58b0beae1f406bd60e