Fix post_build when there is a build failure
https://softwarefactory-project.io/r/11584 introduced a bug where,
if a package build fails, the "failures" variable is not defined,
so DLRN fails with the following traceback:

UnboundLocalError: local variable 'failures' referenced before assignment

Fixing that by making sure the variable is always defined, and also
make sure that we do not display an unnecessary info message when
there is a package failure, about the "consistent" symlink not being
updated.

Change-Id: Ia8ec354ad3461ef5fbfd9a53a8f5cb0022d3d90e