Change column max size users tables
It looks like DLRN cannot create the users tables
on MariaDB due to the size of the username field.
It seems to be related to the use of username as
primary key that exceed the 767 Bytes limitation.

sqlalchemy.exc.InternalError: (pymysql.err.InternalError) (1071, u'Specified key was too long; max key length is 767 bytes') [SQL: u'\nCREATE TABLE users (\n\tusername VARCHAR(256) NOT NULL,
\n\tpassword VARCHAR(256) NOT NULL, \n\tPRIMARY KEY (username)\n)\n\n'] (Background on this error at: http://sqlalche.me/e/2j85)

The database where I get the error is created with
these options "CHARACTER SET utf8 COLLATE utf8_general_ci;"

It seems to be a common issue:
https://stackoverflow.com/questions/1814532/1071-specified-key-was-too-long-max-key-length-is-767-bytes

When username VARCHAR length is set to 255 instead of 256 it
solves the issue.

Change-Id: I87d929030744f19132282e132b58aa13c4f750e5